version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    volumes:
      - ./data/recipesDB:/var/lib/postgresql/13/main
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "recipesDB"
  api:
    depends_on:
      - postgres
    build: .
    ports:
    - "5000:5000"
    environment:
      ASPNETCORE_ConnectionStrings__PostgresDatabaseUrl: ${ASPNETCORE_ConnectionStrings__PostgresDatabaseUrl}
    

