version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "hetisweertijdvoorbier"
      POSTGRES_USER: "infi-michelle"
      POSTGRES_DB: "recipesDB"
  api:
    restart: always
    depends_on:
      - postgres
    build: .
    ports:
    - "5000:5000"
    environment:
      ASPNETCORE_ConnectionStrings__PostgresDatabaseUrl: "User ID=infi-michelle;Password=hetisweertijdvoorbier;Server=localhost;Port=5432;Database=recipesDB;Integrated Security=true;Pooling=true;"